[package]
name = "bfrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive", "cargo"] }
log = "0.4.20"
simple_logger = { version = "4.2.0", default-features = false }
